server.name: kibana
server.host: "0.0.0.0"

elasticsearch.hosts:
    - https://elasticsearch:9200
elasticsearch.username: kibana_system
elasticsearch.password: 9UZCmazZWw7Litg86UdL3sscLRMwLfSXMYV5pR4xGqW5qPB6PhLbeNwiTwzPzHhO
elasticsearch.ssl.certificateAuthorities:
    - /usr/share/kibana/config/certs/ca/ca.crt

xpack.security.encryptionKey: 54b83b7c03fd2abab5f9ee215b4da8eb8794cd01c83fc30b0f1f3a50080f0441
xpack.encryptedSavedObjects.encryptionKey: 54b83b7c03fd2abab5f9ee215b4da8eb8794cd01c83fc30b0f1f3a50080f0441
xpack.reporting.encryptionKey: 54b83b7c03fd2abab5f9ee215b4da8eb8794cd01c83fc30b0f1f3a50080f0441
