name: BDE-dev

services:

    nginx:
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - ./development/certificates:/etc/nginx/certificates
            - ./development/services/nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - '80:80'
            - '443:443'
        develop:
            watch:
                - action: sync+exec
                  path: ./development/services/nginx/nginx.conf
                  target: /etc/nginx/nginx.conf
                  exec:
                      command: nginx -s reload
    postgres:
        ports:
            - '$DATABASE_PORT:5432'

    seaweed-master:
        ports:
            - '9333:9333'

    seaweed-filer:
        ports:
            - '8888:8888'

    seaweed-volume:
        ports:
            - '8080:8080'
