services:
    seaweed-master:
        image: chrislusf/seaweedfs
        command: 'master -ip=seaweed-master -port=9333'
        ports:
            - '9333:9333'
        networks:
            - app
    seaweed-volume:
        image: chrislusf/seaweedfs
        command: 'volume -mserver=seaweed-master:9333 -ip=seaweed-volume -port=8080'
        depends_on:
            - seaweed-master

        ports:
            - '8080:8080'
        networks:
            - app
    seaweed-filer:
        image: chrislusf/seaweedfs
        command: 'filer -master=seaweed-master:9333'
        depends_on:
            - seaweed-master
        ports:
            - '8888:8888'
        networks:
            - app
    dicebear:
        image: dicebear/api:4
        restart: always
        networks:
            - app
        tmpfs:
            - '/run'
            - '/tmp'
        environment:
            WEBP_SIZE_MAX: 512
    nginx:
        build: ./services/nginx
        ports:
            - '80:80'
            - '443:443'
        networks:
            - app
            - host-network
        volumes:
            - ./certificates:/etc/nginx/certificates
        depends_on:
            - seaweed-filer

networks:
    app:
    host-network:
