input {
	beats {
		port => 5044
		ssl_enabled => true
		ssl_certificate_authorities => ['/certs/ca/ca.crt']
		ssl_certificate => '/certs/logstash/logstash.crt'
		ssl_key => '/certs/logstash/logstash.key'
		ssl_client_authentication => 'required'
	}
}

filter {
	if [message] =~ /^\s*\{/ {
		json {
			source => "message"
			skip_on_invalid_json => true
		}
	}
}

output {
	elasticsearch {
		hosts => ['https://elasticsearch:9200']
		user => 'elastic'
		password => '${ELASTIC_PASSWORD}'
		ssl_enabled => true
		ssl_certificate_authorities => ['/certs/ca/ca.crt']
		data_stream => 'true'
		data_stream_type => 'logs'
		data_stream_dataset => 'docker'
		data_stream_namespace => 'default'
	}
}
