user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /run/nginx.pid;


events {
    worker_connections  1024;
}


http {
	include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

	keepalive_timeout  65;
	gzip  on;

    server {
        location / {
			return 301 https://$host$request_uri;
        }
    }

    server {
    	listen 443 ssl;

		ssl_certificate /etc/nginx/certificates/certificate.pem;
		ssl_certificate_key /etc/nginx/certificates/certificate.key.pem;

		access_log  /dev/stdout;
    	error_log   /dev/stderr;

    	location / {
            proxy_pass http://host.docker.internal:3000;

            proxy_set_header Upgrade $http_upgrade;
        	proxy_set_header Connection "upgrade";
        }

        location /app/api/_auth_check {
        	internal;

    		proxy_pass http://host.docker.internal:3000/app/api/auth/info;

    		proxy_pass_request_body off;
			proxy_set_header Cookie $http_cookie;
        }

        location /app/api/_upload_auth_check {
        	internal;

    		proxy_pass http://host.docker.internal:3000/app/api/upload/auth;
    		proxy_pass_request_body off;
			proxy_set_header Content-Length "";
			proxy_set_header X-Original-URI $request_uri;
        }

        location /app/api/upload/ {
        	auth_request /app/api/_upload_auth_check;
        	limit_except POST {
        		deny all;
			}

			proxy_pass http://seaweed-filer:8888/;
			client_max_body_size 10M;
        }

        location /images/upload/ {
       		auth_request /app/api/_auth_check;
        	limit_except GET {
        		deny all;
			}

			proxy_pass http://seaweed-filer:8888/;
        }


    }
}