name: trans-prod

services:
  nginx:
    ports:
      - '0.0.0.0:443:8080'
  node:
    build:
      target: prod
    volumes:
      - node_modules:/home/node/app/node_modules
    environment:
      NODE_ENV: production
    command: [ 'npm', 'run', 'start' ]

  vault:
    volumes:
      - ./docker/vault/vault-prod.hcl:/vault/config/vault.hcl:ro
      - vault_data:/vault/file
    environment:
      VAULT_ADDR: ${VAULT_ADDR}
      VAULT_API_ADDR: ${VAULT_API_ADDR}
    command:
      - server
      - -config=/vault/config/vault.hcl

volumes:
  vault_data:
