services:
    postgres:
        image: postgres:15-alpine
        container_name: $DB_NAME_POSTGRES
        environment:
            POSTGRES_USER: $USER_POSTGRES
            POSTGRES_PASSWORD: $PASSWORD_POSTGRES
            POSTGRES_DB: $DB_NAME_POSTGRES
        ports:
            - '$PORT_POSTGRES:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - main
        restart: on-failure

volumes:
    postgres_data:

networks:
    main:
        driver: bridge
