services:
    postgres:
        image: postgres:15-alpine
        container_name: postgres
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: motdepasse123
            POSTGRES_DB: data
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - main
        restart: on-failure
    caddy:
        image: caddy:alpine
        ports:
            - "443:443"
        volumes:
            - ./docker/Caddyfile:/etc/caddy/Caddyfile
            - caddy_data:/data
            - caddy_config:/config



volumes:
    postgres_data:
    caddy_data:
    caddy_config:

networks:
    main:
        driver: bridge
