name: trans-dev

services:
  nginx:
    environment:
      NGINX_SSL: "1"
    ports:
      - '127.0.0.1:443:443'

  node:
    build:
      target: dev
    volumes:
      - ./:/home/node/app
      - node_modules:/home/node/app/node_modules
    environment:
      NODE_ENV: development
    command: npm run dev

  vault:
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_DEV_ROOT_TOKEN_ID}
      VAULT_ADDR: ${VAULT_ADDR}
    command:
      - server
      - -dev

networks:
  app:
    internal: false
