#!/bin/bash
set -euo pipefail

# shellcheck source=/scripts/wait-utils.sh
source /scripts/wait-utils.sh

CERT_DIR="/usr/share/kibana/config/certs"

# Wait for shared certificates to be generated by elasticsearch bootstrap
wait_for_file "${CERT_DIR}/kibana.crt" 120
wait_for_file "${CERT_DIR}/kibana.key" 120
wait_for_file "${CERT_DIR}/ca.crt" 120

echo "Kibana certificates found."

# Certificates ready — Kibana will be started by the caller entrypoint
