#!/bin/bash
set -euo pipefail

CERT_DIR="/usr/share/kibana/config/certs"

# Wait for shared certificates to be generated by elasticsearch bootstrap
for i in $(seq 1 60); do
    if [ -f "$CERT_DIR/kibana.crt" ] && [ -f "$CERT_DIR/kibana.key" ] && [ -f "$CERT_DIR/ca.crt" ]; then
        echo "Kibana certificates found."
        break
    fi
    echo "Waiting for certificates... ($i/60)"
    sleep 2
done

if [ ! -f "$CERT_DIR/kibana.crt" ]; then
    echo "ERROR: Kibana certificates not found after timeout!" >&2
    exit 1
fi

exec /usr/local/bin/kibana-docker
