name: BDE

services:

    dicebear:
        image: dicebear/api:4
        environment:
            WEBP_SIZE_MAX: 512
        networks:
            - app
        restart: always
        tmpfs:
            - /run
            - /tmp

    nginx:
        image: nginx:stable-alpine
        depends_on:
            - seaweed-filer
        networks:
            - app

    seaweed-master:
        image: chrislusf/seaweedfs
        networks:
            - app
        command: 'master -ip=seaweed-master -port=9333'

    seaweed-filer:
        image: chrislusf/seaweedfs
        depends_on:
            - seaweed-master
        networks:
            - app
        command: 'filer -master=seaweed-master:9333'

    seaweed-volume:
        image: chrislusf/seaweedfs
        depends_on:
            - seaweed-master
        networks:
            - app
        command: 'volume -mserver=seaweed-master:9333 -ip=seaweed-volume -port=8080'

    postgres:
        image: postgres:15-alpine
        container_name: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data

networks:
    app:
        driver: bridge
    host-network:
        driver: bridge

volumes:
    postgres_data:
