server.name: kibana
server.host: 0.0.0.0
server.port: 5601

# Elasticsearch connection
elasticsearch.hosts: [ "https://elasticsearch:9200" ]
elasticsearch.username: kibana_system
elasticsearch.password: ${KIBANA_SYSTEM_PASSWORD}
elasticsearch.ssl.verificationMode: none
xpack.encryptedSavedObjects.encryptionKey: ${KIBANA_ENCRYPTION_KEY}
xpack.security.encryptionKey: ${KIBANA_ENCRYPTION_KEY}
xpack.reporting.encryptionKey: ${KIBANA_ENCRYPTION_KEY}

# Limits
server.maxPayload: 1048576

# Logging
logging.root.level: info
