name: trans-prod

services:
  node:
    build:
      context: ../../
      dockerfile: docker/dev/node/Dockerfile
    ports:
      - '3003:3000'

  # postgres:
  #   image: postgres:15-alpine
  #   container_name: $DB_NAME_POSTGRES
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: $USER_POSTGRES
  #     POSTGRES_PASSWORD: $PASSWORD_POSTGRES
  #     POSTGRES_DB: $DB_NAME_POSTGRES
  #   ports:
  #     - '$PORT_POSTGRES:5432'
  #   networks:
  #     - main
  #   restart: on-failure

networks:
  main:
    driver: bridge

volumes:
  postgres_data:

