services:

    cadvisor:
        image: gcr.io/cadvisor/cadvisor:v0.49.1
        volumes:
            - /:/rootfs
            - /var/run:/var/run
            - /sys:/sys
            - /var/lib/docker/:/var/lib/docker
        networks:
            - monitoring
        restart: unless-stopped
        privileged: true

    node-exporter:
        image: quay.io/prometheus/node-exporter:v1.8.2
        volumes:
            - /:/host
        networks:
            - monitoring
        command:
            - '--path.rootfs=/host'
        restart: unless-stopped
        pid: host

    postgres-exporter:
        image: quay.io/prometheuscommunity/postgres-exporter:v0.16.0
        env_file:
            - ./monitoring/secrets/.env
        networks:
            - monitoring
            - app
        restart: unless-stopped

    elasticsearch-exporter:
        image: quay.io/prometheuscommunity/elasticsearch-exporter:v1.7.0
        volumes:
            - ./services/elasticsearch/certs:/certs
        env_file:
            - ./monitoring/secrets/.env
        networks:
            - monitoring
            - app
        command:
            - '--es.uri=https://elasticsearch:9200'
            - '--es.ca=/certs/ca/ca.crt'
            - '--es.all'
            - '--es.indices'
        restart: unless-stopped
        user: '1000:0'

    nginx-exporter:
        image: nginx/nginx-prometheus-exporter:1.4.0
        networks:
            - monitoring
            - app
        command:
            - '--nginx.scrape-uri=http://nginx:8081/stub_status'
        restart: unless-stopped

    prometheus:
        image: prom/prometheus:v3.1.0
        volumes:
            - ./services/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - ./services/prometheus/alerts.yml:/etc/prometheus/alerts.yml
            - prometheus_data:/prometheus
        networks:
            - monitoring
        restart: unless-stopped

    grafana:
        image: grafana/grafana:11.4.0
        volumes:
            - grafana_data:/var/lib/grafana
            - ./services/grafana/provisioning:/etc/grafana/provisioning
            - ./services/grafana/dashboards:/var/lib/grafana/dashboards
        env_file:
            - ./monitoring/secrets/.env
        networks:
            - monitoring
        restart: unless-stopped

networks:
    monitoring:
        driver: bridge

volumes:
    prometheus_data:
    grafana_data:
