cluster.name: docker-elk
node.name: es01
network.host: 0.0.0.0
discovery.type: single-node
xpack.security.enabled: true
path.repo: ["/usr/share/elasticsearch/data/snapshots"]
indices.queries.cache.size: 10%
indices.fielddata.cache.size: 15%
