api.http.host: 0.0.0.0
api.http.port: 9600

pipeline.workers: 1
pipeline.batch.size: 125
pipeline.batch.delay: 50
pipeline.ordered: false
pipeline.ecs_compatibility: v1

log.level: info

xpack.monitoring.enabled: false

# mTLS input certs
xpack.monitoring.elasticsearch.ssl.certificate_authority: /usr/share/logstash/config/certs/ca.crt
