name: BDE-staging

services:
    elasticsearch:
        ports:
            - '127.0.0.1:9200:9200'

    nginx:
        volumes:
            - ./staging/certificates:/etc/nginx/certificates
        ports:
            - '80:80'
            - '443:443'

    postgres:
        env_file:
            - ./staging/secrets/.env
