[global_tags]

[agent]
  interval = "15s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "15s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false

[[inputs.logstash]]
  url = "http://logstash:9600"

[[inputs.beat]]
  url = "http://filebeat:5066"
  username = ""
  password = ""

[[inputs.elasticsearch]]
  servers = ["https://elasticsearch:9200"]
  username = "${ELASTIC_USERNAME}"
  password = "${ELASTIC_PASSWORD}"
  tls_ca = "/etc/telegraf/certs/ca.crt"
  insecure_skip_verify = true
  cluster_health = true
  cluster_stats = true
  node_stats = ["jvm", "process", "os", "fs", "indices", "thread_pool"]

[[outputs.elasticsearch]]
  urls = ["https://elasticsearch:9200"]
  username = "${ELASTIC_USERNAME}"
  password = "${ELASTIC_PASSWORD}"
  index_name = "telegraf-%Y.%m.%d"
  tls_ca = "/etc/telegraf/certs/ca.crt"
  insecure_skip_verify = true
  health_check_interval = "10s"
  manage_template = true
  template_name = "telegraf"

[[outputs.prometheus_client]]
  listen = ":9273"
  metric_version = 2
  collectors_exclude = ["gocollector", "process"]
