services:
    node:
        build:
            context: ..
            dockerfile: docker/node/Dockerfile
            args:
                NEXT_PUBLIC_OAUTH_42_CLIENTID: ${NEXT_PUBLIC_OAUTH_42_CLIENTID}
                NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
        environment:
            POSTGRES_HOST: postgres
            DATABASE_PORT: 5432
            ELASTICSEARCH_URL: https://elasticsearch:9200
            NODE_EXTRA_CA_CERTS: /certs/ca.crt
        volumes:
            - ./services/elasticsearch/certs/ca/ca.crt:/certs/ca.crt
        depends_on:
            postgres:
                condition: service_healthy
        networks:
            - app
        restart: always
