filebeat.autodiscover:
    providers:
        - type: docker
          templates:
              - config:
                    - type: container
                      paths:
                          - '/var/lib/docker/containers/${data.docker.container.id}/*.log'

processors:
    - add_docker_metadata: ~

output.logstash:
    hosts: ['logstash:5044']
    ssl:
        enabled: true
        certificate_authorities: ['/certs/ca/ca.crt']
        certificate: '/certs/filebeat/filebeat.crt'
        key: '/certs/filebeat/filebeat.key'
