server {
    listen 80;
    server_name ${NEXT_PUBLIC_BASE_URL} grafana.${NEXT_PUBLIC_BASE_URL} kibana.${NEXT_PUBLIC_BASE_URL} prometheus.${NEXT_PUBLIC_BASE_URL};

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name ${NEXT_PUBLIC_BASE_URL};

    ssl_certificate /etc/nginx/certificates/certificate.pem;
    ssl_certificate_key /etc/nginx/certificates/certificate.key.pem;

    access_log /dev/stdout;
    error_log /dev/stderr;

    location / {
        proxy_pass http://${NODE_UPSTREAM};
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location /app/api/_auth_check {
        internal;

        proxy_pass http://${NODE_UPSTREAM}/app/api/auth/info;

        proxy_pass_request_body off;
        proxy_set_header Cookie $http_cookie;
    }

    location /app/api/_upload_auth_check {
        internal;

        proxy_pass http://${NODE_UPSTREAM}/app/api/upload/auth;
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header Content-Type "";
    }

    location /app/api/upload/ {
        client_max_body_size 10M;

        proxy_buffering off;
        proxy_request_buffering off;

        limit_except POST {
            deny all;
        }

        proxy_pass http://seaweed-filer:8888/;
    }

    location /images/upload/ {
        auth_request /app/api/_auth_check;

        limit_except GET {
            deny all;
        }

        proxy_pass http://seaweed-filer:8888/;
    }

    location /images/avatar/ {
        auth_request /app/api/_auth_check;

        limit_except GET {
            deny all;
        }

        rewrite ^/images/avatar/([^/]+)$ /10.x/thumbs/webp?shapeColor=f2f2f2,000000&mouthColor=000000,f2f2f2&backgroundColor=fd84fe,99ffba,9f99ff&seed=$1 break;

        proxy_pass http://dicebear:3000/;
    }

    location /images/organization/avatar/ {
        auth_request /app/api/_auth_check;

        limit_except GET {
            deny all;
        }

        rewrite ^/images/organization/avatar/([^/]+)$ /10.x/shape-grid/svg?rowsVariant=rows02:1&backgroundColor=fd84fe,9f99ff,99ffb1&seed=$1 break;

        proxy_pass http://dicebear:3000/;
    }
}

server {
    listen 443 ssl;
    server_name prometheus.${NEXT_PUBLIC_BASE_URL};

    ssl_certificate /etc/nginx/certificates/certificate.pem;
    ssl_certificate_key /etc/nginx/certificates/certificate.key.pem;

    resolver 127.0.0.11 valid=10s;

    location / {
        set $prometheus_upstream prometheus:9090;
        proxy_pass http://$prometheus_upstream;
        proxy_set_header Host $host;
    }
}

server {
    listen 443 ssl;
    server_name grafana.${NEXT_PUBLIC_BASE_URL};

    ssl_certificate /etc/nginx/certificates/certificate.pem;
    ssl_certificate_key /etc/nginx/certificates/certificate.key.pem;

    resolver 127.0.0.11 valid=10s;

    location / {
        set $grafana_upstream grafana:3000;
        proxy_pass http://$grafana_upstream;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}

server {
    listen 443 ssl;
    server_name kibana.${NEXT_PUBLIC_BASE_URL};

    ssl_certificate /etc/nginx/certificates/certificate.pem;
    ssl_certificate_key /etc/nginx/certificates/certificate.key.pem;

    resolver 127.0.0.11 valid=10s;

    location / {
        set $kibana_upstream kibana:5601;
        proxy_pass http://$kibana_upstream;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}

server {
    listen 8081;

    location /stub_status {
        stub_status;
        allow 172.16.0.0/12;
        allow 127.0.0.1;
        deny all;
    }
}
